name: Your New Jekyll Site
description: Hello, I am the Devel. A front end engineer who loves all things HTML, CSS and Javascript. This is my journal.

meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: false

markdown: kramdown
highlighter: rouge


gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"


baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'develdoe.com'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'John "Devel" Doe'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
